name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:

  lint:
    uses: .github/workflows/lint.yml
    continue-on-error: false

  test:
    uses: .github/workflows/test.yml
    continue-on-error: false

  security:
    uses: .github/workflows/security.yml
    continue-on-error: false

  merge-check:
    needs: [lint, test, security]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Check
        run: |
          if [[ "${{ needs.lint.result }}" == "failure" || "${{ needs.test.result }}" == "failure" || "${{ needs.security.result }}" == "failure" ]]; then
            echo "One of the previous jobs failed. Aborting merge."
            exit 1
          fi
